Repository 2024-Winter-Bootcamp-Team-G/backend, pull requests merged in 2025-01, with the labels that each got.

#5 chore: PostgreSQL 설정, requests 버전 수정
  Dockerfile
  app/db.py
  pyproject.toml
  requirements.txt
Labels: 🧭 Chore, ⛑️ Build

#7 chore: docker-compose.yaml 설정
  app/db.py
  app/main.py
  docker-compose.yaml
  requirements.txt
Labels: 🧭 Chore

#8 [feat] 보드 생성, 목록조회, 상세조회 구현
  app/db.py
  app/init_db.py
  app/main.py
  app/models/__init__.py
  app/models/board.py
  app/routes/board.py
  app/schemas/board.py
  app/services/board_service.py
  app/tests/__init__.py
  app/tests/test_boards.py
  app/tests/test_user.py
  requirements.txt
Labels: 🚀 Feat, ⛑️ Build

#9 feat: 회원가입 및 이메일 중복 확인
  app/main.py
  app/models/__init__.py
  app/models/user.py
  app/routes/__init__.py
  app/routes/user.py
  app/schemas/__init__.py
  app/schemas/user.py
  app/tests/test_signup.py
  app/utils/__init__.py
  requirements.txt
Labels: 🚀 Feat

#14 feat: oauth 리다이렉트, 유튜브 구독 채널 목록 가져오기, 선택한 채널 정보 전송
  app/config.py
  app/main.py
  app/models/SelectedChannelsRequest.py
  app/routes/auth.py
  app/routes/channel.py
  app/routes/subscriptions.py
  app/utils/utils.py
  requirements.txt
Labels: 🚀 Feat

#20 Feat: 보드 공유 구현, oauth 경로 수정
  app/config.py
  app/main.py
  app/routes/auth.py
  app/routes/channel.py
  app/routes/share.py
  app/routes/subscriptions.py
  app/schemas/SelectedChannelsRequest.py
  app/tests/test_share.py
  app/utils/shared_link.py
Labels: 🚀 Feat

#24 [refector] 회원가입, 로그인, 로그아웃 리팩토링함
  app/routes/user.py
  app/services/user_service.py
Labels: 🧹 Refactor

#26 Refactor: 선택한 채널 정보 호출 API(header error) 수정
  app/routes/channel.py
  app/routes/subscriptions.py
Labels: 🧹 Refactor

#30 [fix] DB 관련 오류 해결
  README.md
  app/config.py
  app/init_db.py
  app/routes/channel.py
  app/routes/subscriptions.py
  app/routes/user.py
  app/schemas/board.py
  app/utils/__init__.py
  docker-compose.yaml
Labels: 📑 Docs, 🏷 Fix

#32 refactor: 구독 채널 가져오기 로직 수정
  app/routes/channel.py
Labels: 🧹 Refactor

#34 [feat]redis에 유튜브데이터 저장 구현
  app/routes/channel.py
  app/utils/redis_handler.py
  docker-compose.yaml
Labels: 🚀 Feat

#37 [feat] 동영상 상세 정보 가져오기 구현
  README.md
  app/routes/channel.py
  app/utils/redis_handler.py
Labels: 🚀 Feat

#40 feat: chatgpt 연동, 카테고리와 키워드 추출, 추출된 데이터 DB 저장
  app/main.py
  app/models/board.py
  app/routes/keyword.py
  app/routes/share.py
  app/schemas/board.py
  app/schemas/gpt.py
  app/services/board_service.py
  app/utils/db_handler.py
  app/utils/gpt_handler.py
  app/utils/image_generator.py
  app/utils/redis_handler.py
  app/utils/redis_utils.py
Labels: 🚀 Feat

#43 refactor: DB 내용 수정
  .gitignore
  app/models/board.py
  app/routes/keyword.py
  app/services/gpt_service.py
  app/utils/db_handler.py
Labels: 🧹 Refactor

#47 [refactor] oauth->googleauth 변경
  app/config.py
  app/routes/auth.py
Labels: 🧹 Refactor

#48 keyword 엔드포인트 병합, 카테고리 및 키워드 추출 로직 변경
  app/routes/keyword.py
  app/utils/db_handler.py
  app/utils/gpt_handler.py
Labels: 🧹 Refactor

#52 [refactor] 필요한 작업 주석 추가
  app/services/board_service.py
Labels: 🏷 Fix, 🧹 Refactor

#55 Feat: 선택한 채널 전송 (channel-send 엔드포인트 호출)
  app/routes/channel.py
  app/services/board_service.py
  app/services/channel_service.py
Labels: 🚀 Feat, 🧹 Refactor

#61 [fix] 보드생성 api 수정
  app/routes/board.py
  app/schemas/board.py
  app/services/board_service.py
  app/services/user_service.py
  app/tests/test_gcs.py
  app/utils/dalle_handler.py
  app/utils/gcs_handler.py
  app/utils/redis_handler.py
Labels: 🏷 Fix

#65 fix: 알고리즘 일치율 계산 api 오류해결
  app/routes/board.py
  app/utils/gpt_handler.py
Labels: 🏷 Fix

#69 feat: 프로필 이미지 GCS 저장, url DB 저장, 이미지 조회
  app/config.py
  app/main.py
  app/routes/profile.py
Labels: 🚀 Feat

#73 프로필 조회 로직 수정, profile_img_url 추가, 이미지 재생성 추가
  app/db.py
  app/models/board.py
  app/models/user.py
  app/routes/board.py
  app/routes/profile.py
  app/services/board_service.py
  app/tests/test_regenerate.py
  app/utils/dalle_handler.py
Labels: 🚀 Feat, 🧹 Refactor

#72 [feat]: 보드 링크 공유 api 구현
  app/models/board.py
  app/routes/board.py
  app/routes/share.py
  app/services/auth.py
  app/services/board_service.py
  app/services/user_service.py
Labels: 🚀 Feat

#80 [fix] CORS 도메인 설정
  app/main.py
Labels: 🏷 Fix

#82 [fit] post -> get 수정
  app/routes/user.py
Labels: 🏷 Fix

#83 [fix] 이미지 생성 및 재생성 url 수정
  README.md
  app/schemas/SelectedChannelsRequest.py
  app/utils/dalle_handler.py
  app/utils/gcs_handler.py
Labels: 🏷 Fix

#77 chore: prometheus 환경 추가
  app/main.py
  docker-compose.yaml
  requirements.txt
Labels: 🧭 Chore

#85 프로필 업로드 시 public url 생성으로 수정, googleauth redirect url 수정
  app/routes/auth.py
  app/routes/profile.py
Labels: 🧹 Refactor

#88 [fix]: 보드생성 request body 수정
  app/routes/board.py
  app/schemas/board.py
  app/services/board_service.py
  docker-compose.yaml
Labels: 🏷 Fix, 🧹 Refactor

#89 refactor: 프로필 이미지, googleauth api 수정
  app/routes/auth.py
  app/routes/profile.py
Labels: 🧹 Refactor

#91 refactor: 리다이렉션 url 변경
  app/routes/auth.py
  app/routes/subscriptions.py
Labels: 🧹 Refactor

#94 refactor: 쿠키 수정
  app/routes/auth.py
  app/routes/subscriptions.py
Labels: 🧹 Refactor

#98 [feat] 보드 생성 시 응답 수정
  app/routes/board.py
  app/services/board_service.py
  docker-compose.yaml
Labels: 🚀 Feat

#99 [Refactor] 필요없는 파일 수정, 삭제
  app/routes/gpt.py
  app/routes/profile.py
  app/routes/subscriptions.py
  app/routes/user.py
  app/schemas/gpt.py
  app/schemas/user.py
  app/services/channel_service.py
  app/services/gpt_service.py
  app/services/user_service.py
  app/utils/db_handler.py
  app/utils/redis_utils.py
  app/utils/shared_link.py
Labels: 🚀 Feat, 🧹 Refactor

#101 [feat] 사용자 정보 가져오기 api 구현
  app/routes/profile.py
  app/schemas/user.py
Labels: 🚀 Feat

#103 [fix] 유저정보 수정 후 유저정보 호출시 변경값 반영x 수정
  app/routes/profile.py
Labels: 🏷 Fix

#104 refacotr: googleauth, channel-collect api 수정
  app/routes/auth.py
  app/routes/subscriptions.py
  app/services/google_service.py
Labels: 🧹 Refactor

#107 [fix] redis에 hash 타입으로 youtube_video:{video_id} 저장하도록 변경
  app/services/board_service.py
  app/services/channel_service.py
  app/utils/gpt_handler.py
  app/utils/redis_handler.py
Labels: 🏷 Fix

#109 [feat] 키워드 추출 1차 GPT 프롬프팅 개선
  app/utils/gpt_handler.py
Labels: 🚀 Feat

#113 [Refactor] 키워드 일치율 계산 프롬프트 수정
  app/utils/gpt_handler.py
Labels: 🧹 Refactor

#115 feat] 보드이름 gpt생성, 일치율 계산에 카테고리 출력 추가
  app/services/board_service.py
  app/utils/gpt_handler.py
Labels: 🚀 Feat

#117 [fix] 이미지 생성 함수에서 url 부분, gcs_handler.py 업로드 부분 수정
  app/services/board_service.py
  app/utils/gcs_handler.py
  app/utils/gpt_handler.py
Labels: 🏷 Fix

#119 [feat] 카테고리별로 키워드 재생성 구현
  app/routes/board.py
  app/services/board_service.py
  app/utils/gpt_handler.py
Labels: 🚀 Feat

#120 [fix] 키워드 일치율 프로프팅 수정
  app/routes/board.py
  app/utils/gpt_handler.py
Labels: 🏷 Fix

#122 [feat] UUID로 공유하도록 수정
  app/routes/share.py
Labels: 🚀 Feat

#124 dall-e handler 프롬프트 수정
  app/utils/dalle_handler.py
Labels: 🧹 Refactor

#128 [feat] 알고리즘 일치율 계산 프롬프트 개선
  app/routes/board.py
  app/utils/gpt_handler.py
Labels: 🚀 Feat

#131 [fix] route 수정
  app/main.py
Labels: 🏷 Fix

#133 [fix] 라우터 재설정
  app/main.py
  app/routes/__init__.py
Labels: 🏷 Fix

#134 [feat] config.py,auth.fy redirect url 수정 및 dalle 해상도 및 프롬프트 추가
  app/config.py
  app/routes/auth.py
  app/utils/dalle_handler.py
Labels: 🚀 Feat

#135 [feat] 보드생성 API celery 비동기처리 완료
  app/config.py
  app/main.py
  app/routes/board.py
  app/routes/celery_tasks.py
  app/routes/celery_test.py
  app/services/board_service.py
  app/services/celery_tasks.py
  app/utils/celery_app.py
  app/utils/gpt_handler.py
  docker-compose.yaml
  requirements.txt
Labels: 🚀 Feat
